# Generated by Django 6.0.2 on 2026-03-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_alter_accommodation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='guests',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='max_guests',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='min_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
