# Generated by Django 6.0.2 on 2026-03-01 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_remove_accommodation_guests_accommodation_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='price_per_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='max_guests',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accommodations.accommodation')),
            ],
        ),
    ]
